server:
  port: 8283 #端口
  error:
    whitelabel:
      enabled: false
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
  use-forward-headers: true
spring:
  application:
    name: spring-cloud-feign-inventory #服务名称
  jpa:
    database: mysql
    show-sql: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tcc_stock?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&autoReconnect=true&zeroDateTimeBehavior=round&useSSL=false
    username: root
    password: 123456
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM t_user
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  type-aliases-package: jim.demo.spring.cloud.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  base-package: jim.demo.spring.cloud.mapper
#      # 合并多个DruidDataSource的监控数据
#      useGlobalDataSourceStat: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/
  instance:
     preferIpAddress: true
     lease-expiration-duration-in-seconds: 30
     lease-renewal-interval-in-seconds: 10
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

hmily:
    tcc :
        serializer : kryo
        recoverDelayTime : 128
        retryMax : 30
        scheduledDelay : 128
        scheduledThreadMax :  10
        repositorySupport: redis
        tccRedisConfig:
          hostName: 127.0.0.1
          port: 6379

#        repositorySupport : db
#        tccDbConfig :
#                 driverClassName  : com.mysql.jdbc.Driver
#                 url :  jdbc:mysql://192.168.1.68:3306/tcc?useUnicode=true&amp;characterEncoding=utf8
#                 username : xiaoyu
#                 password : Wgj@555888

       # repositorySupport : redis
       #         hostName  : 192.168.1.68
       #         port      :  6379
       #         password  :


       # repositorySupport : zookeeper
       #         host      : 92.168.1.73:2181
       #         sessionTimeOut      :  100000
       #         rootPath  : /tcc

       # repositorySupport : mongodb
       #       mongoDbUrl  : 192.168.1.68:27017
       #       mongoDbName  :  happylife
       #       mongoUserName  : xiaoyu
       #       mongoUserPwd   : 123456

       # repositorySupport : file
       #         path      : /account
       #         prefix    :  account
