server:
  port: 8180  #端口

eureka:
  instance:
    hostname: localhost #实力名称
    prefer-ip-address: true #暴露ip
  client:
    register-with-eureka: false #是否注册自身到eureka服务器
    fetch-registry: false #是否从eureka服务器获取注册信息
    service-url:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
          #设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 10000 #清理间隙

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jim-YH/spring-cloud-demo.git #配置git仓库地址
          search-paths: config #配置仓库路径
          default-label: master #配置仓库的分支
