server:
  port: 8181 #端口
  error:
    whitelabel:
      enabled: false
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
  use-forward-headers: true
spring:
  application:
    name: spring-cloud-zuul #服务名称
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/
  instance:
     preferIpAddress: true
     lease-expiration-duration-in-seconds: 30
     lease-renewal-interval-in-seconds: 10
zuul:
  routes:
    auth:
        path: /order/**
        serviceId: spring-cloud-feign-order
  host:
    socket-timeout-millis: 120000
    connect-timeout-millis: 120000

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
  threadpool:
    default:
      coreSize: 200 #并发执行的最大线程数，默认10
      maxQueueSize: 200 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 50 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝


